using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Drawing;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Threading;

namespace SamsungDebloater {
 public sealed class MainForm : Form {
  readonly string root=AppDomain.CurrentDomain.BaseDirectory;
  readonly Store store; readonly Engine engine; readonly string logPath;
  Inventory inventory; bool busy,offline,rendering;
  readonly DataGridView grid=new DataGridView();readonly ComboBox profile=new ComboBox(),vendor=new ComboBox(),state=new ComboBox();readonly TextBox search=new TextBox(),details=new TextBox(),log=new TextBox();readonly Label status=new Label(),summary=new Label();readonly List<Control> inputs=new List<Control>();readonly ProgressBar progress=new ProgressBar();
  public MainForm(){
   Text="Samsung App Debloater — 2.0";Size=new Size(1320,850);MinimumSize=new Size(1040,680);StartPosition=FormStartPosition.CenterScreen;Font=new Font("Segoe UI",9);BackColor=Color.FromArgb(245,247,250);
   store=new Store(root);logPath=Path.Combine(root,"logs",Store.Key()+".log");engine=new Engine(new Adb(Path.Combine(root,"platform-tools","adb.exe"),Log),store,Log);
   var layout=new TableLayoutPanel {Dock=DockStyle.Fill,ColumnCount=1,RowCount=8,Padding=new Padding(10)};layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));Controls.Add(layout);
   foreach(int h in new[]{52,76,42,32})layout.RowStyles.Add(new RowStyle(SizeType.Absolute,h));layout.RowStyles.Add(new RowStyle(SizeType.Percent,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,100));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,32));layout.RowStyles.Add(new RowStyle(SizeType.Absolute,110));
   status.Text="SAMSUNG APP DEBLOATER\nConecte o celular por USB e clique em Analisar celular.";status.Font=new Font("Segoe UI",11,FontStyle.Bold);status.Dock=DockStyle.Fill;layout.Controls.Add(status,0,0);
   var actions=new FlowLayoutPanel {Dock=DockStyle.Fill};layout.Controls.Add(actions,0,1);
   Button(actions,"Analisar celular",Analyze);Button(actions,"Otimizar",Optimize);Button(actions,"Restaurar",()=>Restore(null));Button(actions,"Restaurar selecionado",()=>Restore(Selected()==null?null:Selected().Id));Button(actions,"Ver inventário salvo",Preview);Button(actions,"Exportar classificação",Export);
   Button(actions,"Limpar aplicativos",()=>Cleanup(true));
   var filters=new FlowLayoutPanel {Dock=DockStyle.Fill};layout.Controls.Add(filters,0,2);
   filters.Controls.Add(new Label {Text="Perfil:",AutoSize=true,Padding=new Padding(0,6,0,0)});SetupCombo(profile,new[]{"Gaming Seguro","Samsung Gaming Extremo","Personalizado"},205);filters.Controls.Add(profile);
   profile.SelectedIndexChanged+=(s,e)=>{if(inventory!=null){Engine.Profile(inventory,profile.Text);Render();}};
   search.Width=180;filters.Controls.Add(new Label {Text="Pesquisar:",AutoSize=true,Padding=new Padding(8,6,0,0)});filters.Controls.Add(search);inputs.Add(search);search.TextChanged+=(s,e)=>Render();
   SetupCombo(vendor,new[]{"Todos os grupos","Google","Samsung","Meta","Microsoft","System","Outros"},130);filters.Controls.Add(vendor);vendor.SelectedIndexChanged+=(s,e)=>Render();
   SetupCombo(state,new[]{"Todos os estados","ATIVO","DESATIVADO","Com alteração","Protegidos"},145);filters.Controls.Add(state);state.SelectedIndexChanged+=(s,e)=>Render();
   summary.Dock=DockStyle.Fill;summary.Text="MANTER não reativa aplicativos já desativados. Alterações exigem confirmação.";layout.Controls.Add(summary,0,3);
   grid.Dock=DockStyle.Fill;grid.BackgroundColor=Color.White;grid.AllowUserToAddRows=false;grid.AllowUserToDeleteRows=false;grid.RowHeadersVisible=false;grid.MultiSelect=false;grid.SelectionMode=DataGridViewSelectionMode.FullRowSelect;grid.AutoGenerateColumns=false;grid.RowTemplate.Height=28;inputs.Add(grid);
   foreach(var spec in new[]{"Nome|Aplicativo|180","Id|Pacote|310","Grupo|Grupo|85","Estado|Atual|105","Risco|Risco|95","Protecao|Proteção|110"}){var a=spec.Split('|');grid.Columns.Add(new DataGridViewTextBoxColumn{Name=a[0],HeaderText=a[1],Width=int.Parse(a[2]),ReadOnly=true});}
   var action=new DataGridViewComboBoxColumn{Name="Acao",HeaderText="Ação proposta",Width=130};action.Items.AddRange("MANTER","DESATIVAR","REMOVER");grid.Columns.Add(action);
   grid.CurrentCellDirtyStateChanged+=(s,e)=>{if(grid.IsCurrentCellDirty)grid.CommitEdit(DataGridViewDataErrorContexts.Commit);};
   grid.CellValueChanged+=(s,e)=>{if(rendering||e.RowIndex<0||e.ColumnIndex!=6)return;var p=grid.Rows[e.RowIndex].Tag as Package;if(p==null)return;string value=Convert.ToString(grid.Rows[e.RowIndex].Cells[6].Value);try{Engine.Validate(p,value);p.Action=value;UpdateSummary();}catch(Exception ex){MessageBox.Show(this,ex.Message,"Ação bloqueada");rendering=true;grid.Rows[e.RowIndex].Cells[6].Value=p.Action;rendering=false;}};
   grid.DataError+=(s,e)=>{e.ThrowException=false;};grid.SelectionChanged+=(s,e)=>ShowDetails();layout.Controls.Add(grid,0,4);
   details.Multiline=true;details.ReadOnly=true;details.Dock=DockStyle.Fill;details.ScrollBars=ScrollBars.Vertical;details.BackColor=Color.White;layout.Controls.Add(details,0,5);
   progress.Dock=DockStyle.Fill;progress.Style=ProgressBarStyle.Marquee;progress.Visible=false;layout.Controls.Add(progress,0,6);
   log.Multiline=true;log.ReadOnly=true;log.Dock=DockStyle.Fill;log.ScrollBars=ScrollBars.Vertical;layout.Controls.Add(log,0,7);
   FormClosing+=(s,e)=>{if(busy){e.Cancel=true;MessageBox.Show(this,"Aguarde a operação terminar para preservar o registro.");}};
  }
  void SetupCombo(ComboBox box,string[] values,int width){box.DropDownStyle=ComboBoxStyle.DropDownList;box.Items.AddRange(values);box.SelectedIndex=0;box.Width=width;inputs.Add(box);}
  void Button(Control parent,string text,Func<Task> handler){var b=new Button{Text=text,AutoSize=true,Height=32};parent.Controls.Add(b);inputs.Add(b);b.Click+=async(s,e)=>{if(busy)return;busy=true;inputs.ForEach(x=>x.Enabled=false);progress.Visible=true;try{await handler();}catch(Exception ex){Log("ERRO: "+ex.Message);MessageBox.Show(this,ex.Message,"Operação interrompida",MessageBoxButtons.OK,MessageBoxIcon.Warning);}finally{busy=false;inputs.ForEach(x=>x.Enabled=true);progress.Visible=false;}};}
  void Log(string value){File.AppendAllText(logPath,DateTime.Now.ToString("O")+" "+value+Environment.NewLine,Encoding.UTF8);if(value.Length>1500)value=value.Substring(0,1500)+"\r\n[saída completa no arquivo de log]";log.AppendText(value+Environment.NewLine);if(log.TextLength>30000)log.Text=log.Text.Substring(log.TextLength-20000);log.SelectionStart=log.TextLength;log.ScrollToCaret();}
  Package Selected(){return grid.SelectedRows.Count==0?null:grid.SelectedRows[0].Tag as Package;}
  void ShowDetails(){var p=Selected();details.Text=Catalog.ProfileNote(profile.Text)+"\r\n\r\n"+(p==null?"Selecione um aplicativo para ver descrição, impacto e classificação.":p.Info.Name+" — "+p.Id+"\r\n"+p.Info.Description+"\r\n"+p.Info.Reason+"\r\nAPK: "+p.Path+" | Sistema: "+(p.System?"sim":"não")+" | Estado original Android: "+p.Enabled);}
  void UpdateSummary(){if(inventory==null){summary.Text="Analise o celular ou abra o inventário salvo.";return;}summary.Text=String.Format("{0} pacotes • {1} manter • {2} desativar • {3} remover • {4} protegidos | {5}",inventory.Packages.Count,inventory.Packages.Count(p=>p.Action=="MANTER"),inventory.Packages.Count(p=>p.Action=="DESATIVAR"),inventory.Packages.Count(p=>p.Action=="REMOVER"),inventory.Packages.Count(p=>p.Locked),offline?"PRÉVIA OFFLINE — execução bloqueada":"Propostas: selecionar perfil não altera o celular");}
  void Render(){rendering=true;grid.Rows.Clear();if(inventory!=null){foreach(var p in inventory.Packages.Where(p=>(vendor.SelectedIndex<=0||p.Info.Vendor==vendor.Text)&&(state.SelectedIndex<=0||state.Text==p.State||state.Text=="Com alteração"&&p.Action!="MANTER"||state.Text=="Protegidos"&&p.Locked)&&(p.Id+" "+p.Info.Name+" "+p.Info.Description).IndexOf(search.Text,StringComparison.OrdinalIgnoreCase)>=0)){
    int row=grid.Rows.Add(p.Info.Name,p.Id,p.Info.Vendor,p.State,p.Info.Risk,p.Locked?"BLOQUEADO":"Opcional",p.Action);grid.Rows[row].Tag=p;grid.Rows[row].Cells[6].ReadOnly=p.Locked;if(p.Locked)grid.Rows[row].DefaultCellStyle.BackColor=Color.FromArgb(237,240,244);
   }}rendering=false;UpdateSummary();ShowDetails();}
  async Task Analyze(){inventory=null;offline=false;Render();status.Text="Consultando o aparelho; nenhuma alteração está sendo feita...";try{inventory=await engine.Analyze();Engine.Profile(inventory,profile.Text);status.Text=inventory.Model+" | Android "+inventory.Android+" (API "+inventory.Sdk+") | ADB autorizado\n"+(Engine.Compatibility(inventory)??"Compatibilidade prevista; revise as ações.")+" | USB: "+inventory.Serial+" | Inventário salvo em backups";Render();}catch{status.Text="Análise não concluída. Confira USB, autorização e o log.";throw;}}
  public static Inventory LoadEvidence(string root){var e=Path.Combine(root,"evidence");if(!Directory.Exists(e))return DemoInventory.Create();return new Inventory{Serial="PREVIA",Model="SM-G780G",Android="13",Manufacturer="samsung",Sdk=33,Codename="REL",Fingerprint="OFFLINE",Created=DateTime.Now.ToString("O"),Packages=Engine.Parse(File.ReadAllText(Path.Combine(e,"packages-installed.txt")),File.ReadAllText(Path.Combine(e,"packages-system.txt")),File.ReadAllText(Path.Combine(e,"packages-disabled.txt")),File.ReadAllText(Path.Combine(e,"packages-paths.txt")),File.ReadAllText(Path.Combine(e,"package-details.txt")))};}
  Task Preview(){inventory=LoadEvidence(root);offline=true;Engine.Profile(inventory,profile.Text);status.Text=inventory.Serial=="DEMO"?"DEMONSTRAÇÃO — dados fictícios, nenhum celular conectado\nClique em Analisar celular para ler seu próprio aparelho.":"Inventário salvo do S20 FE — prévia offline\nClique em Analisar celular para validar a conexão e habilitar operações.";Render();return Task.FromResult(0);}
  bool Confirm(List<Change> plan,string title,string context=null){using(var dialog=new Form{Text=title,Width=900,Height=620,StartPosition=FormStartPosition.CenterParent,MinimizeBox=false,MaximizeBox=false}){
   var text=new TextBox{Dock=DockStyle.Fill,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,WordWrap=false};text.Text="Aparelho: "+inventory.Model+" / "+inventory.Serial+" | Android "+inventory.Android+"\r\nContexto: "+(context??profile.Text)+" | Usuário 0\r\n\r\nSnapshot = estados e comandos. Não copia dados pessoais nem APKs.\r\nA Play Store desativada pode afetar jogos, licenças e atualizações.\r\nA restauração depende do APK permanecer no firmware.\r\n\r\n"+String.Join("\r\n\r\n",plan.Select(c=>c.Id+"\r\n"+Catalog.Get(c.Id).Description+"\r\n"+String.Join("\r\n",Engine.Commands(c).Select(cmd=>"adb -s "+inventory.Serial+" "+cmd))));
   var panel=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=80};var agree=new CheckBox{Text="Revisei as ações e entendi as funções que deixarão de funcionar.",Width=820,Height=28};var cancel=new Button{Text="Cancelar",DialogResult=DialogResult.Cancel};var run=new Button{Text="Confirmar execução",AutoSize=true,Enabled=false,DialogResult=DialogResult.OK};agree.CheckedChanged+=(s,e)=>run.Enabled=agree.Checked;panel.Controls.Add(agree);panel.Controls.Add(cancel);panel.Controls.Add(run);dialog.Controls.Add(text);dialog.Controls.Add(panel);dialog.CancelButton=cancel;return dialog.ShowDialog(this)==DialogResult.OK;
  }}
  void RequireLive(){if(inventory==null||offline)throw new Exception("Clique em Analisar celular antes de executar ou restaurar.");}
  async Task Optimize(){RequireLive();var plan=Engine.Plan(inventory);if(plan.Count==0){MessageBox.Show(this,"Não há alterações pendentes no perfil. Você pode revisar a limpeza opcional.");await Analyze();await Cleanup(false);return;}if(!Confirm(plan,"Confirmar otimização — "+plan.Count+" aplicativos"))return;try{await engine.Apply(inventory,plan);MessageBox.Show(this,"Operação concluída. Snapshot:\r\n"+engine.LastSnapshot);}finally{inventory=null;Render();status.Text="Faça uma nova análise para atualizar o estado do celular.";}await Analyze();await Cleanup(false);}
  async Task Cleanup(bool refresh){
   if(refresh)await Analyze();RequireLive();var candidates=Engine.CleanupCandidates(inventory);if(candidates.Count==0){MessageBox.Show(this,"Não há aplicativos instalados liberados para esta limpeza. Os componentes protegidos permanecem preservados.");return;}
   List<string> selected;using(var dialog=new CleanupDialog(candidates)){if(dialog.ShowDialog(this)!=DialogResult.OK)return;selected=dialog.SelectedIds;}
   if(selected.Count==0)return;var cleanupInventory=engine.CleanupSelection(inventory,selected);var plan=Engine.Plan(cleanupInventory);if(plan.Count==0){MessageBox.Show(this,"Os aplicativos selecionados já estão desativados. Nenhuma alteração necessária.");return;}if(!Confirm(plan,"Confirmar limpeza opcional — "+plan.Count+" aplicativos","Limpeza opcional (somente aplicativos marcados)"))return;
   try{await engine.Apply(cleanupInventory,plan);MessageBox.Show(this,"Limpeza concluída. Para desfazer, use Restaurar e selecione este snapshot:\r\n"+engine.LastSnapshot);}finally{inventory=null;Render();status.Text="Faça uma nova análise para atualizar o estado do celular.";}await Analyze();
  }
  async Task Restore(string only){RequireLive();using(var picker=new OpenFileDialog{Title="Selecione o snapshot da operação (mais recente primeiro)",InitialDirectory=Path.Combine(root,"backups"),Filter="Snapshots (*.json)|*.json"}){
   if(picker.ShowDialog(this)!=DialogResult.OK)return;var saved=store.Read(picker.FileName);var eligible=saved.Changes.Where(c=>c.Status!="PENDENTE"&&(only==null||c.Id==only)).ToList();if(eligible.Count==0)throw new Exception("Este arquivo não registra alterações desse aplicativo. Escolha o snapshot de otimização ou restauração.");
   using(var choose=new Form{Text="Restaurar todos ou aplicativos individuais",Width=800,Height=500,StartPosition=FormStartPosition.CenterParent}){var list=new CheckedListBox{Dock=DockStyle.Fill,CheckOnClick=true,HorizontalScrollbar=true};foreach(var c in eligible)list.Items.Add(c.Id+" | estado anterior: "+(c.BeforeInstalled?Engine.EnabledCommand(c.BeforeEnabled):"REMOVIDO"),true);var next=new Button{Text="Revisar comandos",Dock=DockStyle.Bottom,Height=36,DialogResult=DialogResult.OK};choose.Controls.Add(list);choose.Controls.Add(next);if(choose.ShowDialog(this)!=DialogResult.OK)return;eligible=eligible.Where((c,index)=>list.GetItemChecked(index)).ToList();}
   var plan=engine.RestorePlan(saved,inventory,eligible.Select(c=>c.Id));if(plan.Count==0){MessageBox.Show(this,"Nenhuma alteração necessária: os aplicativos selecionados já estão no estado original.");return;}if(!Confirm(plan,"Confirmar restauração"))return;try{await engine.Restore(saved,inventory,plan);MessageBox.Show(this,"Restauração concluída e verificada.");}finally{inventory=null;Render();status.Text="Faça uma nova análise para atualizar o estado do celular.";}await Analyze();
  }}
  static string Csv(string s){return "\""+(s??"").Replace("\"","\"\"")+"\"";}
  public void VerifyPreview(string output){Preview().GetAwaiter().GetResult();ShowInTaskbar=false;StartPosition=FormStartPosition.Manual;Location=new Point(-20000,-20000);Show();Application.DoEvents();PerformLayout();if(grid.Rows.Count!=inventory.Packages.Count)throw new Exception("Prévia incompleta");search.Text="com.android.vending";if(grid.Rows.Count!=1)throw new Exception("Pesquisa falhou");search.Clear();vendor.SelectedItem="Meta";if(grid.Rows.Count!=3)throw new Exception("Filtro Meta falhou");vendor.SelectedIndex=0;profile.SelectedItem="Personalizado";if(inventory.Packages.Any(p=>p.Action!="MANTER"))throw new Exception("Perfil personalizado falhou");profile.SelectedIndex=0;Application.DoEvents();using(var bitmap=new Bitmap(Width,Height)){DrawToBitmap(bitmap,new Rectangle(0,0,Width,Height));bitmap.Save(output,System.Drawing.Imaging.ImageFormat.Png);}Hide();}
  public static void WriteReport(Inventory data,string path){var rows=new List<string>{"Pacote;Nome;Grupo;Estado;Acao;Risco;Protegido;Descricao;Motivo;APK"};rows.AddRange(data.Packages.Select(p=>String.Join(";",new[]{p.Id,p.Info.Name,p.Info.Vendor,p.State,p.Action,p.Info.Risk,p.Locked?"Sim":"Não",p.Info.Description,p.Info.Reason,p.Path}.Select(Csv))));File.WriteAllLines(path,rows,Encoding.UTF8);}
  Task Export(){if(inventory==null)throw new Exception("Analise o celular ou abra o inventário salvo.");using(var picker=new SaveFileDialog{FileName="classificacao-samsung.csv",InitialDirectory=root,Filter="CSV (*.csv)|*.csv"}){if(picker.ShowDialog(this)==DialogResult.OK){WriteReport(inventory,picker.FileName);Log("Classificação exportada: "+picker.FileName);}}return Task.FromResult(0);}
  [STAThread] public static void Main(string[] args){
   if(args.Contains("--analyze-only")){var root=AppDomain.CurrentDomain.BaseDirectory;try{var store=new Store(root);string log=Path.Combine(root,"logs",Store.Key()+"-somente-leitura.log");var engine=new Engine(new Adb(Path.Combine(root,"platform-tools","adb.exe"),s=>File.AppendAllText(log,s+Environment.NewLine)),store,s=>File.AppendAllText(log,s+Environment.NewLine));var data=engine.Analyze().GetAwaiter().GetResult();Engine.Profile(data,"S20 FE Gaming Extremo");WriteReport(data,Path.Combine(root,"classificacao-samsung.csv"));File.WriteAllText(Path.Combine(root,"analise-resultado.txt"),data.Model+" | Android "+data.Android+" | "+data.Packages.Count+" pacotes | somente leitura\r\n"+engine.LastSnapshot);Environment.ExitCode=0;}catch(Exception ex){File.WriteAllText(Path.Combine(root,"analise-resultado.txt"),ex.ToString());Environment.ExitCode=1;}return;}
   if(args.Contains("--self-test")){try{Tests.Run(AppDomain.CurrentDomain.BaseDirectory,!args.Contains("--no-ui")).GetAwaiter().GetResult();Environment.ExitCode=0;}catch(Exception ex){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"test-results.txt"),ex.ToString());Environment.ExitCode=1;}return;}
   bool created;using(var mutex=new Mutex(true,"S20FEGamingDebloater_User0",out created)){if(!created){MessageBox.Show("O programa já está aberto. Use uma única janela para evitar operações simultâneas.");return;}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);try{Application.Run(new MainForm());}catch(Exception ex){MessageBox.Show("Não foi possível iniciar: "+ex.Message);}}
  }
 }
}
